version: '3'

# Inicio configuracao do ASP.NET

services:
  sharebook.api:
    image: sharebook
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: Dockerfile      

    networks:
      - sharebook
networks: 
  sharebook: 
    driver: bridge
