version: '3'

services:
  terraform:
    build: ./deploy/docker/terraform
    volumes:
      - .:/terraform

  sharebook.api:
    image: sharebook
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: Dockerfile      

    networks:
      - sharebook

networks: 
  sharebook: 
    driver: bridge
