version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: generate restore graph
          command: |
            dotnet msbuild ShareBook/ShareBook.sln -t:GenerateRestoreGraphFile /p:RestoreGraphOutputPath=/tmp/restore.json
            cat /tmp/restore.json

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "/tmp/restore.json" }}
            - v1-dependencies

      - run:
          name: restore
          command: dotnet restore ShareBook/ShareBook.sln

      - save_cache:
          key: v1-dependencies-{{ checksum "/tmp/restore.json" }}
          paths:
            - ~/.nuget/packages

      - run:
          name: build
          command: dotnet build ShareBook/ShareBook.sln

      - run:
          name: tests
          command: dotnet test ShareBook/ShareBook.Test.Unit/ShareBook.Test.Unit.csproj