version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: restore
          command: dotnet restore ShareBook/ShareBook.sln --verbosity detailed

      - run:
          name: build
          command: dotnet build ShareBook/ShareBook.sln --verbosity detailed