version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@4.0.1

jobs:
  test:
    docker:
      - image: microsoft/dotnet:2.2-sdk

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: generate restore graph
          command: |
            dotnet msbuild -t:GenerateRestoreGraphFile /p:RestoreGraphOutputPath=/tmp/restore.json
            cat /tmp/restore.json

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "/tmp/restore.json" }}
            - v1-dependencies

      - run:
          name: restore
          command: dotnet restore

      - save_cache:
          key: v1-dependencies-{{ checksum "/tmp/restore.json" }}
          paths:
            - ~/.nuget/packages

      - run:
          name: build
          command: dotnet build --no-restore

      - run:
          name: tests
          command: dotnet test ShareBook/ShareBook.Test.Unit/ShareBook.Test.Unit.csproj

workflows:
  version: 2.1
  test_deploy:
    jobs:
      - test
      - aws-ecr/build_and_push_image:
          account-url: AWS_ECR_ACCOUNT_URL
          repo: sharebook
          tag: ${CIRCLE_BRANCH} # This orb does not allow multi-tag yet: https://github.com/CircleCI-Public/aws-ecr-orb/issues/20
          requires:
            - test
          filters:
            branches:
              only:
                - master