version: 2

orbs:
  aws-ecr: circleci/aws-ecr@4.0.1

jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: generate restore graph
          command: |
            dotnet msbuild -t:GenerateRestoreGraphFile /p:RestoreGraphOutputPath=/tmp/restore.json
            cat /tmp/restore.json

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "/tmp/restore.json" }}
            - v1-dependencies

      - run:
          name: restore
          command: dotnet restore

      - save_cache:
          key: v1-dependencies-{{ checksum "/tmp/restore.json" }}
          paths:
            - ~/.nuget/packages

      - run:
          name: build
          command: dotnet build --no-restore

      - run:
          name: tests
          command: dotnet test ShareBook/ShareBook.Test.Unit/ShareBook.Test.Unit.csproj

workflows:
  version: 2
  push_image_prod:
      jobs:
        - aws-ecr/build_and_push_image:
            account-url: PROD_ECR_ACCOUNT_URL
            region: AWS_REGION_ENV_VAR_NAME
            repo: sharebook
            tag: latest