version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk

    working_directory: ~/repo

    steps:
      - checkout

      - run: 
          name: build
          command: dotnet build ShareBook/ShareBook.sln

      - run:
          name: tests
          command: dotnet test ShareBook/ShareBook.sln